### ISSUE TITLE
application-unix: negative timestamps produce erroneous dates

### ISSUE THREAD

**Issue by elydpg** [McTsts/Minecraft-String-Utilities#2]
I was just taking a look at the code that converts unix timestamps into Gregorian dates and I noticed that the code will fail for all timestamps before 1 January, 1970.

In addition, it seems like this module is designed only to support dates in the range of a 32 bit unix timestamp. Is this intentional? Perhaps using a modified Julian day number might be more appropriate for this sort of thing?

**Comment by 5uso** [comment]
The module is mainly intended to interpret the data we get from player skulls, which comes in unix time. We decided to use 32-bit ints since they are implemented into the game. We are aware that this limits the range up to 2038, but it shouldn't be a problem for now.

**Comment by elydpg** [comment]
Good to know. I was also going to mention that the leap year rule is incorrect, although this isn't a problem for dates in the supported range of 32 bit unix timestamps.
