### ISSUE TITLE
ID in callback not working with async

### ISSUE THREAD

**Issue by Command-Master** [McTsts/Minecraft-String-Utilities#5]
Hi, I'm trying to use the command: `/data modify storage string:io queue append value {string:'{"text":"abc"}',ignore:'{"text":"',callback:{command:"function signshop:finish_tp",id:1},async:{iterations:100}}` but after it's run, the scoreboard `callback string` isn't set. What may I do?

**Comment by McTsts** [comment]
Outdated documentation, sorry. Name of the value is `$callback string` now.
Example [here](https://github.com/McTsts/Minecraft-String-Utilities/blob/master/examples/data/example/functions/4_multi.mcfunction).

**Comment by Command-Master** [comment]
Still doesn't work... Is there a way for me to confirm that I have the latest version?

**Comment by Command-Master** [comment]
Also doesn't work with `sync`

**Comment by McTsts** [comment]
If you downloaded it after the latest commit you have the latest version.

**Comment by Command-Master** [comment]
I've downloaded it after the latest commit. this is the version I have: [strings.zip](https://github.com/McTsts/Minecraft-String-Utilities/files/4298758/strings.zip), do I have to download all of the data packs?

**Comment by Command-Master** [comment]
The ID is in string:internal, so I'll load it myself for now
