### ISSUE TITLE
Calling string:call from an async callback

### ISSUE THREAD

**Issue by Command-Master** [McTsts/Minecraft-String-Utilities#6]
Hi, I've tried calling string:call from the callback of an async string read, but it doesn't work. Is there a workaround for this? when I replaced the function call with a `say` and run it manually it works.

**Comment by McTsts** [comment]
I'm not sure what you mean

**Comment by Command-Master** [comment]
when from the callback of the string parsing I run another string parsing it doesn't work

**Comment by McTsts** [comment]
oh yeah, that's intentional. it wont do another string parsing so that you can callback to the function that started the string parsing without it looping

**Comment by McTsts** [comment]
Workaround: `scoreboard players reset $callback string` - it will forget it's in a callback and string parsing can be used again.

**Comment by Command-Master** [comment]
I'll just use schedule, as something is broken with $callback string for me. Is it reset each tick?

**Comment by Command-Master** [comment]
That might be the reason I don't see it

**Comment by Command-Master** [comment]
It worked, tysm
