### ISSUE TITLE
Is there a way to convert from a char array back into a string?

### ISSUE THREAD

**Issue by in2itivity** [McTsts/Minecraft-String-Utilities#8]
I notice that this data pack does not provide a way to convert from the character arrays processed by the strings module back into a single string.

For what reason is this functionality not provided? Is it not possible, or is the process much simpler that a data pack is not required? If the latter, could someone please describe the method that can be used?

**Comment by McTsts** [comment]
It is currently not possible to turn a char array back into a string. The only thing we can do is display a char array as a string (in JSON), but I'm guessing that's not what you're looking for. If it is, then this is how you do it: `tellraw @s {"nbt":"out","storage":"string:io","interpret":true}`

**Comment by in2itivity** [comment]
> @McTsts It is currently not possible to turn a char array back into a string.

Does this mean that it is impossible to concatenate strings in NBT? Because the logical way to convert from char arrays back to strings is by concatenating them. I was hoping to be able to write strings back into NBT to change item data, and this is quite a bummer.

**Comment by McTsts** [comment]
Yes, string concatenations are impossible in NBT. You can use this to add JSON strings into item name/lore, but you can't create custom tags + values dynamically or anything like that.

**Comment by in2itivity** [comment]
@McTsts Sorry to drag this conversation on for long, but do you have any proof of this being impossible? I am currently searching for an answer to ths question on multiple online communities, so if you could provide proof as to why string concatenation in NBT is impossible, that would greatly help me explain on those websites. Thanks!

**Comment by McTsts** [comment]
I don't have any proof, and I guess it's not "impossible", but as far as I know, nobody has any theories, so I'm guessing that means it's impossible. String parsing for example was known long before it became possible (we actually requested a bug to be fixed which made it impossible) so I'm guessing if there was any way to do it, somebody would've figured it out by now.

**Comment by Command-Master** [comment]
You can vote for MC-183054 if you want to turn a char array back to a string

**Comment by in2itivity** [comment]
@Command-Master Could you explain how this would help? I'm getting "Endermen-placed wither skulls can't summon the wither/other missing block updates."

**Comment by Command-Master** [comment]
Structure block's `author` is the name of the entity which placed them, unflattened. If endermans would register placing structure blocks, it would unflatten the string. For more information you can look around the pinned message in the Minceraft Commands Discord's #general

**Comment by in2itivity** [comment]
@Command-Master Okay, I see what you're trying to jab at. Looking around the Discord, I see you've had a long discussion about this. Have you still not found a way to make the enderman place the structure block immediately?

**Comment by Command-Master** [comment]
We have found a way to do that, but it requires spawning ~2000 enderman until you get a good one (though they are killed immediately). The problem is that since MC-183054 isn't fixed that doesn't help because the `author` doesn't get updated as it should

**Comment by Rehennausma** [comment]
Helpful conversation for me.

**Comment by mohammad-sayed-ahmad** [comment]
Wouldn't Enchant Flattening work?

**Comment by McTsts** [comment]
Enchant flattening surrounds the string you are flattening with a lot of additional characters, so it's not actual flattening. Its good for string parsing but not for flattening

**Comment by theMagicMiner** [comment]
as of 1.19.4, you should be able to use the data commands string source with the syntax
string <entity | block | storage> [path] [start] [end]
to splice the desired result out of the output of the enchant flattening process.

**Comment by MaxBQb** [comment]
Since 1.20.2 we have macro-functions, so most of strings can be concatenated with 
```
# _concat.mcfunction
$data modify storage some_storage some_path_to_result set value "$(a)$(b)"
# concat.mcfunction
function some_path_to__concat_macro with storage some_storage some_path_to_source_of_a_and_b
```

BUT, some special chars should be escaped additionally: `'` `"` `\` can cause problems during macro substitution, so they must be escaped.
Well, I've discovered that `set_name` loot function (also can be used with item modify) setting nbt text-component resolve its content (in same tick and context, wich is far more better that waiting for command output) to single text-component with escaped text, so that component can be then trimmed from begin and end to match exact string needed and escaped, wich than can be safely used in macro concatenation. See [this datapack](https://github.com/mcftqb/StructAnim/tree/main/data/struct_anim/functions/utils/str) as example
